"""Regenerates viewer/samples.js from the example specs, using the real builder and validator.

    uv run python scripts/make_viewer_samples.py

A test checks that the committed file matches this output, so it cannot go stale.
"""

import json
from pathlib import Path

from rig_agent.builder.skeleton_builder import build_skeleton
from rig_agent.schemas.rig_spec import RigSpec
from rig_agent.validator.report import validate

ROOT = Path(__file__).resolve().parent.parent
EXAMPLES = ROOT / "examples"
OUTPUT = ROOT / "viewer" / "samples.js"

HEADER = """// Generated by scripts/make_viewer_samples.py. Do not edit by hand.
// Sample skeletons and validation reports built from examples/*.json.
"""


def render() -> str:
    samples = {}
    for path in sorted(EXAMPLES.glob("*.json")):
        spec = RigSpec.model_validate_json(path.read_text(encoding="utf-8"))
        skeleton = build_skeleton(spec, source_prompt=spec.character_summary)
        report = validate(skeleton, spec)
        samples[path.stem] = {
            "skeleton": skeleton.model_dump(mode="json"),
            "report": report.model_dump(mode="json"),
        }
    body = json.dumps(samples, separators=(",", ":"), sort_keys=True)
    return (
        HEADER
        + "(typeof window !== 'undefined' ? window : globalThis).RIG_SAMPLES = "
        + body
        + ";\n"
    )


if __name__ == "__main__":
    OUTPUT.write_text(render(), encoding="utf-8")
    print(f"wrote {OUTPUT} ({OUTPUT.stat().st_size:,} bytes)")
